name = "geometry"
main = "Source/index.ts"
compatibility_date = "2024-05-05"
node_compat = true

rules = [
    { type = "Text", globs = ["./*.js", "./*.html"], fallthrough = true}
]

[placement]
mode = "smart"
